import { useCallback, useEffect, useState } from "react";
import { createAsset, deleteAsset, getAssets, updateAsset } from "../../services/financial.service";
import type { Asset } from "../../types/financial";

export default function AssetManagerV6({ token }: { token: string }) {
  const [items, setItems] = useState<Asset[]>([]); const [edit, setEdit] = useState<Asset | null>(null);
  const load = useCallback(() => getAssets(token).then(setItems), [token]); useEffect(() => { void load(); }, [load]);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const category = String(form.get("category")); const data = { name: category, category, value: Number(form.get("value")), classification: String(form.get("classification")) as Asset["classification"] }; if (edit) { await updateAsset(token, edit.id, data); setEdit(null); } else await createAsset(token, data); event.currentTarget.reset(); await load(); }
  return <main className="min-h-screen bg-slate-950 p-8 text-white"><button onClick={() => window.history.back()} className="text-cyan-400">Volver</button><h1 className="mt-5 text-3xl font-bold">Activos</h1><p className="mt-2 text-slate-400">Un activo productivo genera ingresos; uno no productivo puede conservar valor sin generar flujo.</p><form key={edit?.id ?? "new"} onSubmit={save} className="mt-6 flex max-w-2xl flex-wrap gap-3"><input name="category" defaultValue={edit?.category} className="flex-1 rounded bg-slate-800 p-3" placeholder="Tipo de activo" required /><input name="value" type="number" min="0.01" step="0.01" defaultValue={edit?.value} className="w-32 rounded bg-slate-800 p-3" placeholder="Valor" required /><select name="classification" defaultValue={edit?.classification ?? "non_productive"} className="rounded bg-slate-800 p-3"><option value="productive">Productivo</option><option value="non_productive">No productivo</option></select><button className="rounded bg-cyan-500 px-5 font-semibold text-slate-950">{edit ? "Guardar" : "Agregar"}</button>{edit && <button type="button" onClick={() => setEdit(null)}>Cancelar</button>}</form><div className="mt-8 max-w-2xl space-y-3">{items.map((item) => <div key={item.id} className="flex justify-between rounded bg-slate-900 p-4"><span>{item.category} <em className="text-cyan-300">· {item.classification === "productive" ? "Productivo" : "No productivo"}</em></span><span>S/ {item.value.toFixed(2)} <button onClick={() => setEdit(item)} className="ml-3 text-cyan-400">Editar</button><button onClick={() => void deleteAsset(token, item.id).then(load)} className="ml-3 text-red-400">Eliminar</button></span></div>)}</div></main>;
}
