import { useEffect, useState } from "react";
import { createMortgage, getMortgages, payMortgage } from "../../services/financial.service";
import type { Mortgage } from "../../types/financial";

const types: Mortgage["credit_type"][] = ["Hipotecario", "Vehicular", "Personal", "Empresarial", "Tarjetero", "Otro"];
export default function CreditManager({ token }: { token: string }) {
  const [items, setItems] = useState<Mortgage[]>([]); const [type, setType] = useState<Mortgage["credit_type"]>("Hipotecario"); const [name, setName] = useState(""); const [principal, setPrincipal] = useState(""); const [limit, setLimit] = useState(""); const [rate, setRate] = useState(""); const [months, setMonths] = useState("240");
  const load = () => getMortgages(token).then(setItems); useEffect(() => { void load(); }, [token]);
  async function save(e: React.FormEvent) { e.preventDefault(); await createMortgage(token, { name: name || `Crédito ${type}`, credit_type: type, principal: Number(principal), credit_limit: type === "Tarjetero" ? Number(limit) : null, annual_interest_rate: Number(rate), term_months: Number(months), start_date: new Date().toISOString().slice(0, 10) }); setName(""); setPrincipal(""); setLimit(""); await load(); }
  async function pay(item: Mortgage) { const amount = window.prompt("Monto pagado", String(item.monthly_payment)); if (!amount || Number(amount) <= 0) return; await payMortgage(token, item.id, Number(amount), new Date().toISOString().slice(0, 10)); await load(); }
  return <main className="min-h-screen bg-slate-950 p-8 text-white"><button onClick={() => window.history.back()} className="text-cyan-400">Volver</button><h1 className="mt-5 text-3xl font-bold">Créditos y tarjetas</h1><form onSubmit={save} className="mt-6 grid max-w-4xl gap-3 md:grid-cols-3"><select className="rounded bg-slate-800 p-3" value={type} onChange={(e) => setType(e.target.value as Mortgage["credit_type"])}>{types.map((x) => <option key={x}>{x}</option>)}</select><input className="rounded bg-slate-800 p-3" placeholder="Nombre" value={name} onChange={(e) => setName(e.target.value)} /><input className="rounded bg-slate-800 p-3" type="number" min="0.01" placeholder="Saldo usado o capital" value={principal} onChange={(e) => setPrincipal(e.target.value)} required />{type === "Tarjetero" && <input className="rounded bg-slate-800 p-3" type="number" min="0.01" placeholder="Límite de crédito" value={limit} onChange={(e) => setLimit(e.target.value)} required />}<input className="rounded bg-slate-800 p-3" type="number" min="0" step="0.01" placeholder="Interés anual (%)" value={rate} onChange={(e) => setRate(e.target.value)} required /><input className="rounded bg-slate-800 p-3" type="number" min="1" placeholder="Meses" value={months} onChange={(e) => setMonths(e.target.value)} required /><button className="rounded bg-cyan-500 p-3 font-semibold text-slate-950">Guardar crédito</button></form><div className="mt-8 max-w-4xl space-y-3">{items.map((item) => <article key={item.id} className="rounded bg-slate-900 p-4"><div className="flex justify-between"><b>{item.credit_type}: {item.name}</b><button className="text-cyan-400" onClick={() => void pay(item)}>Registrar cuota</button></div><p className="mt-2">Saldo: S/ {item.current_balance.toFixed(2)} · Cuota: S/ {item.monthly_payment.toFixed(2)} · Interés próximo: S/ {item.next_interest.toFixed(2)}</p>{item.credit_type === "Tarjetero" && <p className="text-slate-400">Límite: S/ {item.credit_limit?.toFixed(2)} · Disponible: S/ {((item.credit_limit ?? 0) - item.current_balance).toFixed(2)}</p>}</article>)}</div></main>;
}
