import { useCallback, useEffect, useState } from "react";
import { getMortgages, updateMortgage } from "../../services/financial.service";
import type { Mortgage } from "../../types/financial";

export default function CreditEditorV2({ token }: { token: string }) {
  const [items, setItems] = useState<Mortgage[]>([]); const [selected, setSelected] = useState<Mortgage | null>(null); const load = useCallback(() => getMortgages(token).then(setItems), [token]); useEffect(() => { void load(); }, [load]);
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); await updateMortgage(token, selected.id, { name: String(form.get("name")), credit_type: selected.credit_type, credit_limit: selected.credit_limit, principal: Number(form.get("principal")), currency: selected.currency, annual_interest_rate: Number(form.get("rate")), term_months: Number(form.get("months")), start_date: selected.start_date }); setSelected(null); await load(); }
  return <main className="min-h-screen bg-slate-950 p-8 text-white"><button onClick={() => window.history.back()} className="text-cyan-400">Volver</button><h1 className="mt-5 text-3xl font-bold">Editar créditos</h1><div className="mt-6 max-w-3xl space-y-3">{items.map((item) => <button key={item.id} onClick={() => setSelected(item)} className="flex w-full justify-between rounded bg-slate-900 p-4 text-left"><span>{item.credit_type}: {item.name}</span><span>Editar</span></button>)}</div>{selected && <form onSubmit={save} className="mt-8 grid max-w-3xl gap-3 rounded bg-slate-900 p-5 md:grid-cols-2"><input name="name" defaultValue={selected.name} className="rounded bg-slate-800 p-3" required /><input name="principal" type="number" min="0.01" step="0.01" defaultValue={selected.principal} className="rounded bg-slate-800 p-3" required /><input name="rate" type="number" min="0" step="0.01" defaultValue={selected.annual_interest_rate} className="rounded bg-slate-800 p-3" required /><input name="months" type="number" min="1" defaultValue={selected.term_months} className="rounded bg-slate-800 p-3" required /><button className="rounded bg-cyan-500 p-3 font-semibold text-slate-950">Guardar cambios</button><button type="button" onClick={() => setSelected(null)} className="rounded bg-slate-700 p-3">Cancelar</button></form>}</main>;
}
