import { useEffect, useState } from "react";
import { getAssets, getExpenses, getIncomes, getLiabilities, getMortgages } from "../../services/financial.service";
import type { Mortgage } from "../../types/financial";

export default function ReportManagerV2({ token }: { token: string }) {
  const [data, setData] = useState({ income: 0, expense: 0, assets: 0, debts: 0 }); const [credits, setCredits] = useState<Mortgage[]>([]);
  useEffect(() => { void Promise.all([getIncomes(token), getExpenses(token), getAssets(token), getLiabilities(token), getMortgages(token)]).then(([incomes, expenses, assets, debts, loans]) => { setData({ income: incomes.reduce((s, x) => s + x.amount, 0), expense: expenses.reduce((s, x) => s + x.amount, 0), assets: assets.reduce((s, x) => s + x.value, 0), debts: debts.reduce((s, x) => s + x.balance, 0) }); setCredits(loans); }); }, [token]);
  const creditTotal = credits.reduce((sum, credit) => sum + credit.current_balance, 0);
  return <main className="min-h-screen bg-slate-950 p-8 text-white"><button onClick={() => window.history.back()} className="text-cyan-400">Volver</button><h1 className="mt-5 text-3xl font-bold">Reporte financiero</h1><div className="mt-8 max-w-4xl space-y-3"><div className="flex justify-between rounded-lg bg-slate-900 p-4"><span>Ingresos</span><b>S/ {data.income.toFixed(2)}</b></div><div className="flex justify-between rounded-lg bg-slate-900 p-4"><span>Gastos</span><b>S/ {data.expense.toFixed(2)}</b></div><div className="flex justify-between rounded-lg bg-slate-900 p-4"><span>Deudas generales</span><b>S/ {data.debts.toFixed(2)}</b></div><div className="flex justify-between rounded-lg bg-slate-900 p-4"><span>Total de créditos</span><b className="text-red-400">S/ {creditTotal.toFixed(2)}</b></div><div className="flex justify-between rounded-lg bg-slate-900 p-4"><span>Patrimonio neto</span><b>S/ {(data.assets - data.debts - creditTotal).toFixed(2)}</b></div></div><section className="mt-8 max-w-4xl"><h2 className="text-xl font-semibold">Reporte de créditos</h2>{credits.length === 0 ? <p className="mt-3 text-slate-400">No tienes créditos registrados.</p> : <div className="mt-4 space-y-3">{credits.map((credit) => <article key={credit.id} className="rounded-lg bg-slate-900 p-4"><div className="flex justify-between gap-4"><b>{credit.credit_type}: {credit.name}</b><span className="text-red-400">S/ {credit.current_balance.toFixed(2)}</span></div><p className="mt-2 text-sm text-slate-400">Cuota: S/ {credit.monthly_payment.toFixed(2)} · Próximo pago: {credit.next_due_date} · Meses pendientes: {credit.remaining_months}</p>{credit.credit_type === "Tarjetero" && <p className="mt-1 text-sm text-slate-400">Límite disponible: S/ {((credit.credit_limit ?? 0) - credit.current_balance).toFixed(2)}</p>}</article>)}</div>}</section></main>;
}
