"""add_funds_percentages

Revision ID: 31e70ca358c6
Revises: b7fce4fcad98
Create Date: 2026-07-14 23:07:55.799527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e70ca358c6'
down_revision: Union[str, Sequence[str], None] = 'b7fce4fcad98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('donation_percentage', sa.Float(), nullable=False))
    op.add_column('profiles', sa.Column('quality_of_life_percentage', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'quality_of_life_percentage')
    op.drop_column('profiles', 'donation_percentage')
    # ### end Alembic commands ###
