"""Add currency column to all financial entities

Revision ID: 3f39c6be1cc5
Revises: 86a45fe69949
Create Date: 2026-07-14 22:46:28.458175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f39c6be1cc5'
down_revision: Union[str, Sequence[str], None] = '86a45fe69949'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('currency', sa.String(length=3), nullable=False, server_default='PEN'))
    op.add_column('incomes', sa.Column('currency', sa.String(length=3), nullable=False, server_default='PEN'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incomes', 'currency')
    op.drop_column('expenses', 'currency')
    # ### end Alembic commands ###
