"""Add is_paid to expenses

Revision ID: 924ecc57a1d1
Revises: 31e70ca358c6
Create Date: 2026-07-15 07:46:25.708568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924ecc57a1d1'
down_revision: Union[str, Sequence[str], None] = '31e70ca358c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'is_paid')
    # ### end Alembic commands ###
