"""Add currency to assets, liabilities, mortgages

Revision ID: b7fce4fcad98
Revises: 3f39c6be1cc5
Create Date: 2026-07-14 22:47:54.432003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7fce4fcad98'
down_revision: Union[str, Sequence[str], None] = '3f39c6be1cc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('currency', sa.String(length=3), nullable=False, server_default='PEN'))
    op.add_column('liabilities', sa.Column('currency', sa.String(length=3), nullable=False, server_default='PEN'))
    op.add_column('mortgages', sa.Column('currency', sa.String(length=3), nullable=False, server_default='PEN'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mortgages', 'currency')
    op.drop_column('liabilities', 'currency')
    op.drop_column('assets', 'currency')
    # ### end Alembic commands ###
